### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by toadouyang** [WindySha/Xpatch#18]
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.merge(SimpleLiveAnalyze.java:100)
        at com.googlecode.dex2jar.ir.ts.an.SimpleLiveAnalyze.merge(SimpleLiveAnalyze.java:27)
        at com.googlecode.dex2jar.ir.ts.Cfg.dfs(Cfg.java:274)
        at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze0(BaseAnalyze.java:75)
        at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:69)
        at com.googlecode.dex2jar.ir.ts.Ir2JRegAssignTransformer.transform(Ir2JRegAssignTransformer.java:182)
        at com.googlecode.d2j.dex.Dex2jar$2.optimize(Dex2jar.java:269)
        at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:453)
        at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:40)
        at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:169)
        at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:600)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:445)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:357)
        at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:464)
        at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:277)
        at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:377)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:118)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:293)
        at com.storm.wind.xpatch.task.ApkModifyTask.dex2JarCmd(ApkModifyTask.java:87)
        at com.storm.wind.xpatch.task.ApkModifyTask.dumpJarFile(ApkModifyTask.java:68)
        at com.storm.wind.xpatch.task.ApkModifyTask.run(ApkModifyTask.java:40)
        at com.storm.wind.xpatch.MainCommand.doCommandLine(MainCommand.java:165)
        at com.storm.wind.xpatch.base.BaseCommand.doMain(BaseCommand.java:123)
        at com.storm.wind.xpatch.MainCommand.main(MainCommand.java:56)

**Comment by WindySha** [comment]
是破解哪个apk出现的问题

**Comment by toadouyang** [comment]
破解微信的时候，系统是win10

**Comment by toadouyang** [comment]
解决：跟jdk有关，重新下载之后没有问题了，谢谢！
