### ISSUE TITLE
xpatch-2.0 打开应用crash

### ISSUE THREAD

**Issue by lanshifu** [WindySha/Xpatch#26]
2019-05-31 11:15:45.220 18009-18009/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lanshifu.opengldemo, PID: 18009
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lanshifu.opengldemo-RVQTGiQDpgX-tcIwiDG8mw==/base.apk"],nativeLibraryDirectories=[/data/app/com.lanshifu.opengldemo-RVQTGiQDpgX-tcIwiDG8mw==/lib/arm64, /system/lib64]]] couldn't find "libsandhook.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.swift.sandhook.SandHookConfig$1.loadLib(Unknown Source:6)
        at com.swift.sandhook.SandHook.<clinit>(Unknown Source:16)
        at com.swift.sandhook.SandHook.passApiCheck(Unknown Source:0)
        at com.wind.xposed.entry.XposedModuleEntry.init(:1)
        at com.lanshifu.opengldemo.MainApplication.<clinit>(Unknown Source:0)

测试机型：三星、华为  ，so没找到

**Comment by WindySha** [comment]
打包任何应用都是so找不到？
在这个目录下： data/app/com.lanshifu.opengldemo-RVQTGiQDpgX-tcIwiDG8mw==/lib/arm64
能看到libsandhook.so文件吗？

**Comment by lanshifu** [comment]
我是在公司的window系统操作，出的问题，
现在在家里用mac操作，目标：简书、腾讯视频
安装能正常打开和加载xposed模块，华为也不崩溃了，2.0更换hook框架解决了华为崩溃的问题哦，可以可以，👍
