### ISSUE TITLE
打包后直接闪退咋整

### ISSUE THREAD

**Issue by RabbitcoreDEV** [WindySha/Xpatch#45]
报错

```
E/ReflectionUtils(2580): error get methods
E/ReflectionUtils(2580): java.lang.reflect.InvocationTargetException
E/ReflectionUtils(2580): 	at java.lang.reflect.Method.invoke(Native Method)
E/ReflectionUtils(2580): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ReflectionUtils(2580): 	at com.swift.sandhook.utils.ReflectionUtils.<clinit>()
E/ReflectionUtils(2580): 	at com.swift.sandhook.SandHook.passApiCheck()
E/ReflectionUtils(2580): 	at com.wind.xposed.entry.XposedModuleEntry.init(:1)
E/ReflectionUtils(2580): 	at com.yiimuu.rich_dinosaur.RdApp.<clinit>(Unknown Source)
E/ReflectionUtils(2580): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/ReflectionUtils(2580): 	at java.lang.Class.newInstance(Class.java:1606)
E/ReflectionUtils(2580): 	at android.app.Instrumentation.newApplication(Instrumentation.java:995)
E/ReflectionUtils(2580): 	at android.app.Instrumentation.newApplication(Instrumentation.java:980)
E/ReflectionUtils(2580): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
E/ReflectionUtils(2580): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
E/ReflectionUtils(2580): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
E/ReflectionUtils(2580): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
E/ReflectionUtils(2580): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ReflectionUtils(2580): 	at android.os.Looper.loop(Looper.java:135)
E/ReflectionUtils(2580): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/ReflectionUtils(2580): 	at java.lang.reflect.Method.invoke(Native Method)
E/ReflectionUtils(2580): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ReflectionUtils(2580): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/ReflectionUtils(2580): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/ReflectionUtils(2580): Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
E/ReflectionUtils(2580): 	at java.lang.Class.getMethod(Class.java:664)
E/ReflectionUtils(2580): 	at java.lang.Class.getDeclaredMethod(Class.java:626)
E/ReflectionUtils(2580): 	... 21 more
```

**Comment by WindySha** [comment]
先用1.4版本的jar包试试吧

**Comment by RabbitcoreDEV** [comment]
> 先用1.4版本的jar包试试吧
1.4报错这个
```
 E/Whale(2834): [2834] Unable to launch on houdini environment.
 E/Whale(2834): Runtime setup failed
 E/Xposed(2834): de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.UnsatisfiedLinkError: JNI_ERR retur
 E/Xposed(2834): 	at de.robv.android.xposed.XposedHelpers.callStaticMethod(Unknown Source)
 E/Xposed(2834): 	at de.robv.android.xposed.XposedBridge.hookMethod(Unknown Source)
 E/Xposed(2834): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source)
 E/Xposed(2834): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source)
 E/Xposed(2834): 	at com.eridanus.dragonHook.DragonHook.hookSignature(DragonHook.java:39)
 E/Xposed(2834): 	at com.eridanus.dragonHook.DragonHook.handleLoadPackage(DragonHook.java:34)
 E/Xposed(2834): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source)
 E/Xposed(2834): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source)
 E/Xposed(2834): 	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source)
 E/Xposed(2834): 	at com.wind.xposed.entry.b.a(Unknown Source)
 E/Xposed(2834): 	at com.wind.xposed.entry.XposedModuleEntry.init(Unknown Source)
 E/Xposed(2834): 	at com.yiimuu.rich_dinosaur.RdApp.<clinit>(Unknown Source)
 E/Xposed(2834): 	at java.lang.reflect.Constructor.newInstance(Native Method)
 E/Xposed(2834): 	at java.lang.Class.newInstance(Class.java:1606)
 E/Xposed(2834): 	at android.app.Instrumentation.newApplication(Instrumentation.java:995)
 E/Xposed(2834): 	at android.app.Instrumentation.newApplication(Instrumentation.java:980)
 E/Xposed(2834): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
 E/Xposed(2834): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
 E/Xposed(2834): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
 E/Xposed(2834): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
 E/Xposed(2834): 	at android.os.Handler.dispatchMessage(Handler.java:102)
 E/Xposed(2834): 	at android.os.Looper.loop(Looper.java:135)
 E/Xposed(2834): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
 E/Xposed(2834): 	at java.lang.reflect.Method.invoke(Native Method)
 E/Xposed(2834): 	at java.lang.reflect.Method.invoke(Method.java:372)
 E/Xposed(2834): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
 E/Xposed(2834): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
 E/Xposed(2834): Caused by: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.yiimuu.rich
 E/Xposed(2834): 	at java.lang.Runtime.loadLibrary(Runtime.java:390)
 E/Xposed(2834): 	at java.lang.System.loadLibrary(System.java:1007)
 E/Xposed(2834): 	at com.lody.whale.WhaleRuntime.<clinit>(Unknown Source)
 E/Xposed(2834): 	at de.robv.android.xposed.WhaleXposedBridge.hookMethod(Unknown Source)
 E/Xposed(2834): 	at java.lang.reflect.Method.invoke(Native Method)
 E/Xposed(2834): 	at java.lang.reflect.Method.invoke(Method.java:372)
 E/Xposed(2834): 	... 27 more
```

**Comment by RabbitcoreDEV** [comment]
找不到类
`E/AndroidRuntime(5050): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "reflectmaster.anti." on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex", dex file "/data/dalvik-cache/xposed_XTypedArraySuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]`

**Comment by RabbitcoreDEV** [comment]
大佬可以顺便通过一下群申请吗，加不进群

**Comment by WindySha** [comment]
whale的so文件找不到  把破解的apk解压出来  看看lib目录下面有没有相关的so文件

**Comment by WindySha** [comment]
3.0版本修复此问题
