### ISSUE TITLE
重新打包出错！

### ISSUE THREAD

**Issue by igit-cn** [WindySha/Xpatch#47]
IMAC:Desktop IMAC$ java -jar ./xpatch-3.0.jar ./WeChat_7.0.3（1381）Google\ Play\ \[0305\].apk
 !!!!! output apk path -->  ./WeChat_7.0.3（1381）Google Play [0305]-xposed-signed.apk  disableCrackSignature --> false
java.lang.NullPointerException
	at com.storm.wind.xpatch.util.ApkSignatureHelper.getApkSignInfo(ApkSignatureHelper.java:75)
	at com.storm.wind.xpatch.task.SaveApkSignatureTask.run(SaveApkSignatureTask.java:26)
	at com.storm.wind.xpatch.MainCommand.doCommandLine(MainCommand.java:151)
	at com.storm.wind.xpatch.base.BaseCommand.doMain(BaseCommand.java:125)
	at com.storm.wind.xpatch.MainCommand.main(MainCommand.java:83)
 Get original signature failed !!!!

**Comment by IGIT-CN** [comment]
谷歌商店版微信

**Comment by WindySha** [comment]
获取签名信息失败，只是无法绕过签名校验，重打包可以正常使用
