### ISSUE TITLE
jdk13和jdk14上获取证书失败，报空指针错误，如下所示

### ISSUE THREAD

**Issue by cjycjw** [WindySha/Xpatch#58]
java.lang.NullPointerException
	at com.storm.wind.xpatch.util.ApkSignatureHelper.getApkSignInfo(ApkSignatureHelper.java:77)
	at com.storm.wind.xpatch.task.SaveApkSignatureTask.run(SaveApkSignatureTask.java:26)
	at com.storm.wind.xpatch.MainCommand.doCommandLine(MainCommand.java:151)
	at com.storm.wind.xpatch.base.BaseCommand.doMain(BaseCommand.java:125)
	at com.storm.wind.xpatch.MainCommand.main(MainCommand.java:83)
 Get original signature failed !!!!

**Comment by WindySha** [comment]
`-c,--crach                   disable craching the apk's signature.`

**Comment by WindySha** [comment]
`-c,--crach                   disable craching the apk's signature.`
加这个命令，关闭过签名的功能试试看

**Comment by cjycjw** [comment]
关闭签名是可以，不过因为包有签名校验关闭后也有问题，已经改用直接读取*.RSA文件获取证书来解决，不知道为什么jdk13和jdk14通过JarEntry方式获取证书就是空的！
