### ISSUE TITLE
本地代码直接配置参数后直接运行会报错

### ISSUE THREAD

**Issue by liangxiwei** [WindySha/Xpatch#67]
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.storm.wind.xpatch.util.FileUtils.copyFileFromJar(FileUtils.java:113)
	at com.storm.wind.xpatch.task.SoAndDexCopyTask.copyLibFile(SoAndDexCopyTask.java:151)
	at com.storm.wind.xpatch.task.SoAndDexCopyTask.copySoFile(SoAndDexCopyTask.java:88)
	at com.storm.wind.xpatch.task.SoAndDexCopyTask.run(SoAndDexCopyTask.java:57)
	at com.storm.wind.xpatch.MainCommand.doCommandLine(MainCommand.java:221)
	at com.storm.wind.xpatch.base.BaseCommand.doMain(BaseCommand.java:125)
	at com.storm.wind.xpatch.MainCommand.main(MainCommand.java:83)
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.storm.wind.xpatch.util.FileUtils.copyFileFromJar(FileUtils.java:113)
	at com.storm.wind.xpatch.task.SoAndDexCopyTask.copyDexFile(SoAndDexCopyTask.java:127)
	at com.storm.wind.xpatch.task.SoAndDexCopyTask.run(SoAndDexCopyTask.java:58)
	at com.storm.wind.xpatch.MainCommand.doCommandLine(MainCommand.java:221)
	at com.storm.wind.xpatch.base.BaseCommand.doMain(BaseCommand.java:125)
	at com.storm.wind.xpatch.MainCommand.main(MainCommand.java:83)
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.storm.wind.xpatch.util.FileUtils.copyFileFromJar(FileUtils.java:113)
	at com.storm.wind.xpatch.task.BuildAndSignApkTask.run(BuildAndSignApkTask.java:50)
	at com.storm.wind.xpatch.MainCommand.doCommandLine(MainCommand.java:221)
	at com.storm.wind.xpatch.base.BaseCommand.doMain(BaseCommand.java:125)
	at com.storm.wind.xpatch.MainCommand.main(MainCommand.java:83)
Failed to load signer "signer #1"
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658)
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
	at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
	at com.storm.wind.xpatch.task.BuildAndSignApkTask.signApkUsingAndroidApksigner(BuildAndSignApkTask.java:144)
	at com.storm.wind.xpatch.task.BuildAndSignApkTask.signApk(BuildAndSignApkTask.java:68)
	at com.storm.wind.xpatch.task.BuildAndSignApkTask.run(BuildAndSignApkTask.java:52)
	at com.storm.wind.xpatch.MainCommand.doCommandLine(MainCommand.java:221)
	at com.storm.wind.xpatch.base.BaseCommand.doMain(BaseCommand.java:125)
	at com.storm.wind.xpatch.MainCommand.main(MainCommand.java:83)

**Comment by liangxiwei** [comment]
如果是本地跑就有问题，但打包出一个jar就没问题。
