### ISSUE TITLE
下标越界了

### ISSUE THREAD

**Issue by makejavas** [WindySha/Xpatch#8]
java.lang.ArrayIndexOutOfBoundsException: 1850
        at wind.android.content.res.StringBlock.getShort(StringBlock.java:234)
        at wind.android.content.res.StringBlock.getString(StringBlock.java:94)
        at wind.android.content.res.AXmlResourceParser.getName(AXmlResourceParser.java:145)
        at com.storm.wind.xpatch.util.ManifestParser.parseManidestFile(ManifestParser.java:43)
        at com.storm.wind.xpatch.MainCommand.doCommandLine(MainCommand.java:140)
        at com.storm.wind.xpatch.base.BaseCommand.doMain(BaseCommand.java:123)
        at com.storm.wind.xpatch.MainCommand.main(MainCommand.java:56)

**Comment by WindySha** [comment]
如何复现问题

**Comment by WindySha** [comment]
3.0版本修复此问题
