### ISSUE TITLE
更新不上了

### ISSUE THREAD

**Issue by junges521** [WindySha/Xpatch#83]
Caused by: android.content.res.Resources$NotFoundException: File null from xml type layout resource ID #0x7f0400dc
        at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1222)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2183)
        at android.content.res.Resources.getLayout(Resources.java:1169)
        at android.taobao.atlas.runtime.DelegateResources.getLayout(DelegateResources.java:275)
        at java.lang.reflect.Method.invoke(Native Method)
        at de.robv.android.xposed.MethodHooker.handleHookedMethod(MethodHooker.java:81)
        at EdHooker_12165eeeee1c6fd1ebc4d77cfad471b8eed052e8.hook(Unknown Source:52)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:176)
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:154)
        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)
        at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs32.stub_hook_6(MethodHookerStubs32.java:236)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.yunos.tvtaobao.splashscreen.activity.StartActivity.generateView(StartActivity.java:95)
        at com.yunos.tvtaobao.splashscreen.activity.StartActivity.onCreate(StartActivity.java:87)
        at android.app.Activity.performCreate(Activity.java:7232)
        at android.app.Activity.performCreate(Activity.java:7221)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.taobao.atlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:681)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840) 
        at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:288) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6878) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by junges521** [comment]
使用天猫魔盒m21pro 去hook电视淘宝会有问题，  java.lang.RuntimeException: 7.3.20DelegateResources paths are: newDelegateResources [/data/app/com.yunos.tvtaobao-SZi_n6qHsQSfcUWLQ3qvGA==/base.apk,/data/user/0/com.yunos.tvtaobao/lib/libcom_yunos_tvtaobao_live.so,]
        at android.taobao.atlas.runtime.ActivityThreadHook.handleMessage(ActivityThreadHook.java:364)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
