### ISSUE TITLE
打包SoulApp后崩溃

### ISSUE THREAD

**Issue by polarbear88** [WindySha/Xpatch#91]
2021-09-06 15:22:24.351 31028-31028/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.soulapp.android, PID: 31028
    java.lang.ExceptionInInitializerError
        at cn.soulapp.android.client.component.middle.platform.utils.d2.a.a.a(SoundManager.java:1)
        at cn.soulapp.android.component.square.recommend.TimeLineFragment.b(TimeLineFragment.java:7)
        at cn.soulapp.android.component.square.BaseSquareFragment.onResume(BaseSquareFragment.kt:3)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:5)
        at androidx.fragment.app.FragmentStateManager.m(FragmentStateManager.java:3)
        at androidx.fragment.app.FragmentManager.u0(FragmentManager.java:29)
        at androidx.fragment.app.FragmentManager.t0(FragmentManager.java:1)
        at androidx.fragment.app.FragmentManager.r0(FragmentManager.java:4)
        at androidx.fragment.app.FragmentManager.s0(FragmentManager.java:6)
        at androidx.fragment.app.FragmentManager.I(FragmentManager.java:3)
        at androidx.fragment.app.FragmentManager.G(FragmentManager.java:3)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:10)
        at androidx.fragment.app.FragmentStateManager.m(FragmentStateManager.java:3)
        at androidx.fragment.app.FragmentManager.u0(FragmentManager.java:29)
        at androidx.fragment.app.FragmentManager.t0(FragmentManager.java:1)
        at androidx.fragment.app.FragmentManager.r0(FragmentManager.java:4)
        at androidx.fragment.app.BackStackRecord.g(BackStackRecord.java:26)
        at androidx.fragment.app.FragmentManager.Q(FragmentManager.java:6)
        at androidx.fragment.app.FragmentManager.R(FragmentManager.java:14)
        at androidx.fragment.app.FragmentManager.C0(FragmentManager.java:10)
        at androidx.fragment.app.FragmentManager.P(FragmentManager.java:5)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:2)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:4)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:51)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:25)
        at android.view.View.measure(View.java:25176)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25176)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25176)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:14)
        at androidx.recyclerview.widget.LinearLayoutManager.V(LinearLayoutManager.java:11)
        at androidx.recyclerview.widget.LinearLayoutManager.F(LinearLayoutManager.java:9)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:65)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:13)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:2)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:8)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
2021-09-06 15:22:24.351 31028-31028/? E/AndroidRuntime:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1139)
        at android.view.View.layout(View.java:22511)
        at android.view.ViewGroup.layout(ViewGroup.java:6528)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3731)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3195)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2154)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8872)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
        at android.view.Choreographer.doFrame(Choreographer.java:911)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: android.content.res.Resources$NotFoundException: File res/raw/sound_pull.mp3 from drawable resource ID #0x7f100080
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:535)
        at android.content.res.Resources.openRawResourceFd(Resources.java:1445)
        at android.media.SoundPool.load(SoundPool.java:224)
        at cn.soulapp.android.client.component.middle.platform.utils.d2.a.a.<init>(SoundManager.java:14)
        at cn.soulapp.android.client.component.middle.platform.utils.d2.a.a.<init>(SoundManager.java:1)
        at cn.soulapp.android.client.component.middle.platform.utils.d2.a.a$b.<clinit>(SoundManager.java:1)
        	... 98 more
     Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
        at android.content.res.AssetManager.nativeOpenNonAssetFd(Native Method)
        at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:1099)
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:529)
        	... 103 more

打开不崩溃，登录账号进去后就崩溃

**Comment by WindySha** [comment]
资源被压缩问题  下个版本修复

**Comment by polarbear88** [comment]
请问是否有临时解决方案呢

**Comment by WindySha** [comment]
new version v4.3 released, and solved this bug.
