### ISSUE TITLE
4.2保错

### ISSUE THREAD

**Issue by Mortalit** [WindySha/Xpatch#92]
Error: A JNI erpor has occurred, please check your installation and try again
Exception in thread \
/xpatch/MainConmand has heen compiled by a more recent version of the Java Runt
ime (class file version 55.0), this version of the Java Runtime only recognizes
class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader. defineClass (Unknoun Source)
at java.security.SecureClassloader. defineClass (Unknown Source)
at iava.net.URLClassTnader. def ineclass (llnknoun Source)
at iava.net.URLClassLoader. access$109(Unknown Source)
at java.net.URLClassLoaders1.run (Unknown Source)
at .iava.net.URLClassLoaders1.Fun (Unknown Source)
at .iava.security.AccessController.doPrivileged(Native Method)
at iava.net.URLClassLoader.findClass (Unknoun Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.LaunchersAppClassLoader. loadClass (Unknown Source)
at java.lang.ClassLoader.loadClass (Unknown Source)
at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

win上使用的,java是最新版本,4.0和4.1无问题

**Comment by WindySha** [comment]
需要把java版本从8升级到11
